scenic:
  verifaiSamplerType: 'mab'
  is_easy: False
  is_medium: False
  is_hard: True

supervisor:
  base_model: "PPO_vacuum_agent_latest_arsalan_trainedbykay.zip"
  model_name: "hi"
  max_steps: 10000
  episodes: 50
  is_training: True

simulator:
  truncate: True

training:
  training_method: "EL"
  use_plr: False
  use_verifai: False
  buffer_p: 0.5
  output_to_csv: False
  


